name: llm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.7
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - statsmodels
  - tqdm
  - jupyterlab
  - black
  - pre-commit
  - pip
